### ISSUE TITLE
Shutterstock

### ISSUE THREAD

**Issue by abdullahkhursheed22** [abdullahkhursheed22/factsilove#11]
File name: /resources/images/ant-abilities-3.jpg
Website link: https://www.shutterstock.com/
Media link: https://www.shutterstock.com/editorial/image-editorial/wood-ants-squirt-formic-acid-into-the-air-to-deter-aerial-predators-from-their-nest-dorset-britain-mar-2014-3682491e

**Comment by Hamath-Eltrael** [comment]
Hey, so I can't access https://www.shutterstock.com/editorial/image-editorial/ as it isn't available in my region. So you'd have to find out what they licensed that picture under. Sorry for that, but there's nothing I can do about it.

**Comment by abdullahkhursheed22** [comment]
> So you'd have to find out what they licensed that picture under.

This is what the website says:

![image](https://github.com/abdullahkhursheed22/factsilove/assets/134539459/8d029d26-2975-4792-a553-c3f7b2cc9657)

**Comment by Hamath-Eltrael** [comment]
Ok, so we are golden here, nothing to do for images from shutterstock, as long as we don't make any money off of it.

I recommend _you_ close this issue, to mark it as the license is covered. 

Do continue to post new images as comments as before though! As I'm closing this issue, to find it in the future you have to remove "is:open" in the searchbar of the issues:
<img width="858" alt="Bildschirmfoto 2023-07-10 um 21 59 54" src="https://github.com/abdullahkhursheed22/factsilove/assets/60324384/a166830d-b62d-422c-a609-ad7155b5d4bd">

**Comment by Hamath-Eltrael** [comment]
And Again, not legal advice! ^^

**Comment by abdullahkhursheed22** [comment]
Understood!
